tools:
  submit_testcmd:
    signature: "submit_testcmd"
    docstring: "submits the test commands and the following three log files were generated: /home/run.log, /home/fix-patch-run.log, and /home/test-patch-run.log. "
    arguments: []
